[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
swap = "C6E82rhkqDHB3PsccYffy9A3HyU9sBnT6gkWTNcrERBT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ahmed/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
